"""add whatsapp_orders table

Revision ID: cb5edb100649
Revises: 001_initial
Create Date: 2026-09-01 09:29:00.924204

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb5edb100649'
down_revision: Union[str, None] = '001_initial'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('whatsapp_orders',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('grizzly_activation_id', sa.String(length=100), nullable=False),
    sa.Column('phone_number', sa.String(length=30), nullable=False),
    sa.Column('country', sa.String(length=10), nullable=False),
    sa.Column('supplier_price', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('charged_price', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('otp_received', sa.String(length=50), nullable=True),
    sa.Column('full_sms', sa.Text(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_whatsapp_orders_grizzly_activation_id'), 'whatsapp_orders', ['grizzly_activation_id'], unique=True)
    op.create_index(op.f('ix_whatsapp_orders_status'), 'whatsapp_orders', ['status'], unique=False)
    op.create_index(op.f('ix_whatsapp_orders_telegram_id'), 'whatsapp_orders', ['telegram_id'], unique=False)
    op.create_index(op.f('ix_whatsapp_orders_user_id'), 'whatsapp_orders', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_whatsapp_orders_user_id'), table_name='whatsapp_orders')
    op.drop_index(op.f('ix_whatsapp_orders_telegram_id'), table_name='whatsapp_orders')
    op.drop_index(op.f('ix_whatsapp_orders_status'), table_name='whatsapp_orders')
    op.drop_index(op.f('ix_whatsapp_orders_grizzly_activation_id'), table_name='whatsapp_orders')
    op.drop_table('whatsapp_orders')
    # ### end Alembic commands ###
